---
title: Os Paxariños
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ospaxarinhos@gmail.com
description: <center><h2>Blog da Casa niño "Os paxariños".</h2></center>
baseurl: ''
url: https://byemege.github.io/
markdown: kramdown
include:
- ".htaccess"
